---
- name: "k8s install | Include OS-specific variables."
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: setup-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when:
    - ansible_os_family == 'Debian'

- include_tasks: setup-generic.yml

# Set up masters.
- include_tasks: master-setup.yml
  when:
    - inventory_hostname in groups['kube_master']
    - kubernetes_install_only is not defined

# Set up nodes.
- include_tasks: node-setup.yml
  when:
    - inventory_hostname in groups['kube_node']
    - kubernetes_install_only is not defined

# Set up what's required for networking.
- include_tasks: setup-networking.yml
  when:
    - kubernetes_pod_network.yaml_manifest is defined
    - kubernetes_pod_network.yaml_manifest | length > 0

# Apply additional configuration
- include_tasks: kubectl-apply.yml
