---
- name: "kubeadm | master | Fetch images required for master components"
  command: "kubeadm config images pull --kubernetes-version={{ kubernetes_version_kubeadm }}"
  when:
    - not kubeadmin_file.stat.exists

- name: "kubeadm | master | Initialize first master"
  include_tasks: kubeadm-init.yml
  when:
    - inventory_hostname == groups['kube_master'][0]
    - not kubeadmin_file.stat.exists

- name: "kubeadm | master | Create join token."
  include_tasks: kubeadm-token.yml

- name: "kubeadm | master | Join other master to the cluster"
  include_tasks: kubeadm-join.yml
  when:
    - inventory_hostname != groups['kube_master'][0]
    - not kubeadmin_file.stat.exists

- name: "k8s install | master | Ensure .kube directory exists."
  file:
    path: ~/.kube
    state: directory

- name: "k8s install | master |Symlink the kubectl admin.conf to ~/.kube/conf."
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link


## TODO: Check if taint exists with something like `kubectl describe nodes`
## instead of using kubernetes_init_stat.stat.exists check.
- name: "k8s install | master | Allow pods on master node (if configured)."
  command: "kubectl taint nodes --all node-role.kubernetes.io/master-"
  when:
    - inventory_hostname != groups['kube_master'][0]
    - not kubernetes_init_stat.stat.exists
    - kubernetes_allow_pods_on_master | bool
