---
- name: "Setup | Networking | Bridge traffic traverse iptables"
  lineinfile:
    dest: /etc/sysctl.d/k8s.conf
    regexp: '^net.bridge.bridge-nf-call-iptables'
    line: 'net.bridge.bridge-nf-call-iptables = 1'
    create: yes
  notify: sysctl apply


- name: "Setup | Networking | Prepare CNI Addon yaml manifest to be executed."
  set_fact:
    kubernetes_apply_yml_manifests:
      "{{ kubernetes_apply_yml_manifests|default([]) }} +
        ['{{ kubernetes_pod_network.yaml_manifest }}']
      "
  run_once: true
