---
- name: "k8s install | Ensure dependencies are installed."
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: "k8s install | Add Kubernetes apt key."
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  register: add_repository_key
  ignore_errors: "{{ kubernetes_apt_ignore_key_error }}"

- name: "k8s install | Add Kubernetes repository."
  apt_repository:
    repo: "{{ kubernetes_apt_repository }}"
    state: present
    update_cache: true

- name: "k8s install | Add Kubernetes apt preferences file to pin a version."
  template:
    src: apt-preferences-kubernetes.j2
    dest: /etc/apt/preferences.d/kubernetes
